modLoader="javafml" #mandatory
loaderVersion="[32,)" #mandatory
license="Legopitstop Common License"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="ediblebamboo" #mandatory

version="1.0.1" #mandatory

displayName="Edible Bamboo" #mandatory
updateJSONURL="https://raw.githubusercontent.com/legopitstop/ModUpdates/master/EdibleBamboo/update.json"
displayURL="http://example.com/"
logoFile="ediblebamboo.png"
credits=""
authors="Legopitstop"
description='''
Have you ever wanted to eat bamboo like pandas? Well with this mod you can! you can even smoke it to make it more yummy!
'''

[[dependencies.ediblebamboo]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ediblebamboo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
